<?php
/**
 * Copyright (c) Mage-OS. Licensed under OSL-3.0.
 * See LICENSE.txt for license details.
 */

declare(strict_types=1);

// NOTE: the gate (validationRelevantFieldsChanged) reloads the stored row, so
// unlike ValidateWorkflowOnSaveFiresTest this suite must supply the plugin's
// WorkflowFactory and resource model. MageOS\Workflows\Model\WorkflowFactory is
// one of Magento's per-model factories, generated by the object manager at
// install/build time and never part of a module's committed source, so this
// file declares a minimal stand-in under that exact namespace using PHP's
// bracketed multi-namespace syntax — the same technique DispatcherTest uses
// (see dev/tests/shims/README.md for the equivalent convention applied to
// third-party classes, which that autoloader deliberately does not extend to
// MageOS\* namespaces). The resource model is real: only its DB-touching
// load() is overridden, by a subclass declared in the test namespace.

namespace MageOS\Workflows\Model {

    use MageOS\Workflows\Api\Data\WorkflowInterface;

    /**
     * Standalone-runner stand-in for the generated WorkflowFactory. Hands back
     * a caller-supplied blank model instead of asking an object manager.
     */
    class WorkflowFactory
    {
        /** @var callable(): WorkflowInterface */
        private $creator;

        public function __construct(callable $creator)
        {
            $this->creator = $creator;
        }

        public function create(array $data = []): WorkflowInterface
        {
            return ($this->creator)();
        }
    }
}

namespace MageOS\Workflows\Test\Unit\Plugin {

    use MageOS\Workflows\Api\Data\WorkflowInterface;
    use MageOS\Workflows\Model\ResourceModel\Workflow as WorkflowResource;
    use MageOS\Workflows\Model\Validation\ValidationResult;
    use MageOS\Workflows\Model\Validation\ValidationResultRegistry;
    use MageOS\Workflows\Model\WorkflowFactory;
    use MageOS\Workflows\Plugin\ValidateWorkflowOnSave;
    use MageOS\Workflows\Test\Unit\Stub\WorkflowStub;
    use PHPUnit\Framework\TestCase;
    use Psr\Log\NullLogger;

    /**
     * The save-validation gate on an EXISTING workflow: which field changes
     * re-run the F2 pipeline and which are waved through.
     *
     * Both directions matter. Re-pointing a trigger (type, ref or entity type)
     * without touching the definition is exactly how a workflow acquires an
     * unparseable cron expression or an event nobody dispatches, so it must
     * validate. A status-only save must still skip: mass enable/disable has to
     * keep working on a workflow whose stored definition no longer validates
     * (its action module was uninstalled), or it cannot be turned off.
     */
    class ValidateWorkflowOnSaveGateTest extends TestCase
    {
        /**
         * @param array<string, mixed> $stored
         */
        private function plugin(GateSpyValidator $validator, array $stored): ValidateWorkflowOnSave
        {
            $plugin = (new \ReflectionClass(ValidateWorkflowOnSave::class))->newInstanceWithoutConstructor();
            $this->setProp($plugin, 'validator', $validator);
            $this->setProp($plugin, 'contextResolver', new GateContextResolver());
            $this->setProp($plugin, 'resultRegistry', new ValidationResultRegistry());
            $this->setProp($plugin, 'logger', new NullLogger());
            $this->setProp($plugin, 'workflowFactory', new WorkflowFactory(
                static fn (): WorkflowInterface => new WorkflowStub($stored)
            ));
            $this->setProp($plugin, 'workflowResource', new StoredRowResource());

            return $plugin;
        }

        private function setProp(object $obj, string $name, mixed $value): void
        {
            $prop = new \ReflectionProperty($obj, $name);
            $prop->setValue($obj, $value);
        }

        /**
         * @return array<string, mixed>
         */
        private function storedRow(): array
        {
            return [
                'workflow_id' => 7,
                'status' => WorkflowInterface::STATUS_ENABLED,
                'definition' => '{"schema":3,"entry":"s1","steps":{"s1":{"type":"stop"}}}',
                'conditions_serialized' => '{"type":"root"}',
                'trigger_type' => WorkflowInterface::TRIGGER_TYPE_SCHEDULE,
                'trigger_ref' => '0 3 * * *',
                'entity_type' => 'sales_order',
            ];
        }

        /**
         * @param array<string, mixed> $overrides
         */
        private function incoming(array $overrides): WorkflowStub
        {
            return new WorkflowStub($overrides + $this->storedRow());
        }

        private function ranFor(WorkflowStub $incoming): GateSpyValidator
        {
            $validator = new GateSpyValidator(new ValidationResult([]));
            $this->plugin($validator, $this->storedRow())
                ->beforeSave(new NullWorkflowRepository(), $incoming);

            return $validator;
        }

        public function testStatusOnlyChangeStillSkipsValidation(): void
        {
            $validator = $this->ranFor($this->incoming(['status' => WorkflowInterface::STATUS_DISABLED]));

            $this->assertFalse($validator->called, 'Mass enable/disable must never re-judge a stored definition');
        }

        public function testNameOnlyChangeStillSkipsValidation(): void
        {
            $validator = $this->ranFor($this->incoming(['name' => 'Renamed']));

            $this->assertFalse($validator->called);
        }

        public function testTriggerRefChangeNowValidates(): void
        {
            $validator = $this->ranFor($this->incoming(['trigger_ref' => 'every tuesday-ish']));

            $this->assertTrue($validator->called, 'A re-pointed trigger_ref must reach the check pool');
            $this->assertSame('every tuesday-ish', $validator->subject?->getTriggerRef());
        }

        public function testTriggerTypeChangeNowValidates(): void
        {
            $validator = $this->ranFor($this->incoming([
                'trigger_type' => WorkflowInterface::TRIGGER_TYPE_EVENT,
                'trigger_ref' => 'sales.order.created',
            ]));

            $this->assertTrue($validator->called);
        }

        public function testEntityTypeChangeNowValidates(): void
        {
            $validator = $this->ranFor($this->incoming(['entity_type' => 'customer']));

            $this->assertTrue($validator->called);
        }

        public function testDefinitionChangeStillValidates(): void
        {
            $validator = $this->ranFor($this->incoming([
                'definition' => '{"schema":3,"entry":"s2","steps":{"s2":{"type":"stop"}}}',
            ]));

            $this->assertTrue($validator->called);
        }
    }

    /**
     * Records that validate() ran and returns a scripted result (the sibling
     * of ValidateWorkflowOnSaveFiresTest's spy, kept file-local so neither
     * suite depends on the other having been loaded first).
     */
    class GateSpyValidator extends \MageOS\Workflows\Model\Validation\WorkflowValidator
    {
        public bool $called = false;

        public ?\MageOS\Workflows\Model\Validation\ValidationSubject $subject = null;

        // Bypass the parent constructor (it wants the check chain).
        public function __construct(private readonly ValidationResult $scripted)
        {
        }

        public function validate(
            \MageOS\Workflows\Model\Validation\ValidationSubject $subject,
            \MageOS\Workflows\Model\Validation\ValidationContext $context
        ): ValidationResult {
            $this->called = true;
            $this->subject = $subject;
            return $this->scripted;
        }
    }

    class GateContextResolver extends \MageOS\Workflows\Model\Validation\ValidationContextResolver
    {
        public function __construct()
        {
        }

        public function resolve(): \MageOS\Workflows\Model\Validation\ValidationContext
        {
            return new \MageOS\Workflows\Model\Validation\ValidationContext(
                \MageOS\Workflows\Model\Validation\ValidationContext::MODE_ADMIN_CONTEXT
            );
        }
    }

    /**
     * The stored row is supplied by the factory stand-in, so loading is a
     * no-op — this exists only to keep the plugin off a real DB connection.
     */
    class StoredRowResource extends WorkflowResource
    {
        public function __construct()
        {
        }

        /**
         * @param mixed $object
         * @param mixed $value
         * @param string|null $field
         * @return $this
         */
        public function load($object, $value, $field = null)
        {
            return $this;
        }
    }

    /**
     * Proceeds without side effects: beforeSave never calls through, but the
     * plugin signature wants a repository.
     */
    class NullWorkflowRepository implements \MageOS\Workflows\Api\WorkflowRepositoryInterface
    {
        public function save(WorkflowInterface $workflow): WorkflowInterface
        {
            return $workflow;
        }

        public function getById(int $workflowId): WorkflowInterface
        {
            throw new \RuntimeException('not used');
        }

        public function getList(
            \Magento\Framework\Api\SearchCriteriaInterface $searchCriteria
        ): \Magento\Framework\Api\SearchResultsInterface {
            throw new \RuntimeException('not used');
        }

        public function delete(WorkflowInterface $workflow): bool
        {
            throw new \RuntimeException('not used');
        }

        public function deleteById(int $workflowId): bool
        {
            throw new \RuntimeException('not used');
        }
    }
}
