<?php

declare(strict_types=1);

// NOTE: Dispatcher's constructor is typed against
// MageOS\Workflows\Api\Data\WorkflowExecutionInterfaceFactory — one of Magento's
// per-interface factories, generated by the object manager at install/build
// time and never part of a module's committed source (see
// dev/tests/shims/README.md for the equivalent convention applied to
// third-party generated classes, which that autoloader deliberately does not
// extend to MageOS\* namespaces). This file therefore uses PHP's bracketed
// multi-namespace syntax — the same technique dev/tests/standalone-runner.php
// itself uses to declare its PHPUnit\Framework\TestCase shim — to declare a
// minimal stand-in under that exact namespace, hoisted before the test class
// that needs it, scoped to this file only.

namespace MageOS\Workflows\Api\Data {

    /**
     * Standalone-runner stand-in for the generated WorkflowExecutionInterfaceFactory.
     * Wraps a caller-supplied creator instead of an object manager.
     */
    class WorkflowExecutionInterfaceFactory
    {
        /** @var callable(array): WorkflowExecutionInterface */
        private $creator;

        public function __construct(callable $creator)
        {
            $this->creator = $creator;
        }

        public function create(array $data = []): WorkflowExecutionInterface
        {
            return ($this->creator)($data);
        }
    }
}

namespace MageOS\Workflows\Test\Unit\Model\Engine {

    use Magento\Framework\App\ResourceConnection;
    use Magento\Framework\MessageQueue\PublisherInterface;
    use MageOS\Workflows\Api\Data\WorkflowExecutionInterface;
    use MageOS\Workflows\Api\Data\WorkflowExecutionInterfaceFactory;
    use MageOS\Workflows\Api\Data\WorkflowInterface;
    use MageOS\Workflows\Api\WorkflowExecutionRepositoryInterface;
    use MageOS\Workflows\Api\WorkflowRepositoryInterface;
    use MageOS\Workflows\Model\Engine\Dispatcher;
    use MageOS\Workflows\Model\Suppression\WorkflowSuppression;
    use MageOS\Workflows\Test\Unit\Stub\StubScopeConfig;
    use MageOS\Workflows\Test\Unit\Stub\StubStoreManager;
    use MageOS\Workflows\Test\Unit\Stub\WorkflowExecutionStub;
    use MageOS\Workflows\Test\Unit\Stub\WorkflowStub;
    use Psr\Log\NullLogger;
    use PHPUnit\Framework\TestCase;

    /**
     * Dispatcher::dispatch() accepts a $triggerType and, until now, silently
     * dropped it (issue #2): docs/05-triggers.md promises manual runs record
     * trigger_type=manual on the execution, and the manual/scheduled/event
     * call sites already pass meaningful values through DispatcherInterface.
     * These tests pin down the fix at the dispatch() -> createExecution()
     * seam: whatever trigger type the caller passes lands on the saved
     * execution, and omitting it keeps the documented 'event' default.
     */
    class DispatcherTest extends TestCase
    {
        private WorkflowSuppression $suppression;

        public function setUp(): void
        {
            $this->suppression = new WorkflowSuppression(new StubScopeConfig());
        }

        public function tearDown(): void
        {
            // Defensive: never let a leftover suppression depth leak into the
            // next test file (mirrors SuppressionBypassTest's cleanup).
            while ($this->suppression->isSuppressed()) {
                WorkflowSuppression::restore();
            }
        }

        private function workflow(): WorkflowStub
        {
            return (new WorkflowStub(42))
                ->setStatus(WorkflowInterface::STATUS_ENABLED)
                ->setEntityType('sales_order')
                ->setName('Order follow-up');
        }

        private function workflowRepository(WorkflowInterface $workflow): WorkflowRepositoryInterface
        {
            return new class ($workflow) implements WorkflowRepositoryInterface {
                public function __construct(private readonly WorkflowInterface $workflow)
                {
                }

                public function save(WorkflowInterface $workflow): WorkflowInterface
                {
                    return $workflow;
                }

                public function getById(int $workflowId): WorkflowInterface
                {
                    return $this->workflow;
                }

                public function getList(
                    \Magento\Framework\Api\SearchCriteriaInterface $searchCriteria
                ): \Magento\Framework\Api\SearchResultsInterface {
                    throw new \RuntimeException('not used');
                }

                public function delete(WorkflowInterface $workflow): bool
                {
                    return true;
                }

                public function deleteById(int $workflowId): bool
                {
                    return true;
                }
            };
        }

        /**
         * Records every execution handed to save(); returns it unchanged
         * (mirrors the real repository's persist-and-return contract).
         */
        private function executionRepository(): WorkflowExecutionRepositoryInterface
        {
            return new class implements WorkflowExecutionRepositoryInterface {
                /** @var WorkflowExecutionInterface[] */
                public array $saved = [];

                public function save(WorkflowExecutionInterface $execution): WorkflowExecutionInterface
                {
                    $this->saved[] = $execution;
                    return $execution;
                }

                public function getById(int $executionId): WorkflowExecutionInterface
                {
                    throw new \RuntimeException('not used');
                }

                public function getByUuid(string $uuid): WorkflowExecutionInterface
                {
                    throw new \RuntimeException('not used');
                }

                public function getList(
                    \Magento\Framework\Api\SearchCriteriaInterface $searchCriteria
                ): \Magento\Framework\Api\SearchResultsInterface {
                    throw new \RuntimeException('not used');
                }
            };
        }

        /**
         * A ResourceConnection whose debounce INSERT always succeeds (no
         * duplicate-key collision), and whose getTableName() is the identity
         * function — enough for dispatch()'s debounce write, nothing more.
         */
        private function resourceConnection(): ResourceConnection
        {
            return new class extends ResourceConnection {
                public function __construct()
                {
                }

                public function getConnection($resourceName = self::DEFAULT_CONNECTION)
                {
                    return new class {
                        /** @var array<int, array> */
                        public array $inserted = [];

                        public function insert($table, array $bind)
                        {
                            $this->inserted[] = $bind;
                            return 1;
                        }
                    };
                }

                public function getTableName($modelEntity, $connectionName = self::DEFAULT_CONNECTION)
                {
                    return (string) $modelEntity;
                }
            };
        }

        private function publisher(): PublisherInterface
        {
            return new class implements PublisherInterface {
                /** @var array<int, array{topic: string, data: mixed}> */
                public array $published = [];

                public function publish($topicName, $data)
                {
                    $this->published[] = ['topic' => $topicName, 'data' => $data];
                    return null;
                }
            };
        }

        private function dispatcher(WorkflowInterface $workflow): Dispatcher
        {
            return new Dispatcher(
                $this->workflowRepository($workflow),
                $this->executionRepository(),
                new WorkflowExecutionInterfaceFactory(
                    static fn (array $data = []): WorkflowExecutionInterface => new WorkflowExecutionStub()
                ),
                $this->suppression,
                new StubStoreManager(),
                new StubScopeConfig(),
                $this->resourceConnection(),
                $this->publisher(),
                new NullLogger()
            );
        }

        public function testDispatchRecordsGivenTriggerType(): void
        {
            $dispatcher = $this->dispatcher($this->workflow());

            $execution = $dispatcher->dispatch(
                42,
                ['entity_id' => 5],
                WorkflowInterface::TRIGGER_TYPE_MANUAL
            );

            $this->assertNotNull($execution);
            $this->assertSame(WorkflowInterface::TRIGGER_TYPE_MANUAL, $execution->getTriggerType());
        }

        public function testDispatchRecordsScheduleTriggerType(): void
        {
            $dispatcher = $this->dispatcher($this->workflow());

            $execution = $dispatcher->dispatch(
                42,
                ['entity_id' => 6],
                WorkflowInterface::TRIGGER_TYPE_SCHEDULE
            );

            $this->assertNotNull($execution);
            $this->assertSame(WorkflowInterface::TRIGGER_TYPE_SCHEDULE, $execution->getTriggerType());
        }

        public function testDispatchDefaultsTriggerTypeToEvent(): void
        {
            $dispatcher = $this->dispatcher($this->workflow());

            // $triggerType omitted entirely — DispatcherInterface's default applies.
            $execution = $dispatcher->dispatch(42, ['entity_id' => 7]);

            $this->assertNotNull($execution);
            $this->assertSame(WorkflowInterface::TRIGGER_TYPE_EVENT, $execution->getTriggerType());
        }

        public function testSavedExecutionCarriesTheSameTriggerType(): void
        {
            $repository = $this->executionRepository();
            $dispatcher = new Dispatcher(
                $this->workflowRepository($this->workflow()),
                $repository,
                new WorkflowExecutionInterfaceFactory(
                    static fn (array $data = []): WorkflowExecutionInterface => new WorkflowExecutionStub()
                ),
                $this->suppression,
                new StubStoreManager(),
                new StubScopeConfig(),
                $this->resourceConnection(),
                $this->publisher(),
                new NullLogger()
            );

            $dispatcher->dispatch(42, ['entity_id' => 8], WorkflowInterface::TRIGGER_TYPE_MANUAL);

            $this->assertCount(1, $repository->saved);
            $this->assertSame(WorkflowInterface::TRIGGER_TYPE_MANUAL, $repository->saved[0]->getTriggerType());
        }
    }
}
